### ISSUE TITLE
Data linking to multiple custom properties

### ISSUE THREAD

**Issue by MetoooRepo** [BorisMoore/jsviews.com#4]
Hi Boris,
Look at this fiddle:
https://jsfiddle.net/d3h80vww/ (Commit 64 )

Data-linking to multiple custom properties doesn't seem to work anymore.

In Commit 63 it worked flawlessly.

https://jsfiddle.net/9sshxv3x/ (Commit 63 )

Am i missing something?

**Comment by BorisMoore** [comment]
Thanks for calling this out. It is probably a dup of this: https://github.com/BorisMoore/jsviews/issues/306 (BTW better to put jsviews bugs/issues on that project, rather than the jsviews.com one - which is just for the jsviews.com site).

I'm on vacation, but when I return in about a week's time, I'll look into this issue...

**Comment by MetoooRepo** [comment]
Yes sorry i realized later and tried to remove this issue with no success.
Have a nice vacation!

Il 03/07/2015 19:21, Boris Moore ha scritto:

**Comment by BorisMoore** [comment]
Oh - no problem!

**Comment by BorisMoore** [comment]
Yes, this is a bug. The fix is simply to remove the two lines:

https://github.com/BorisMoore/jsviews/blob/master/jsviews.js#L3227-L3228.

I'll include that fix in the next update.

**Comment by BorisMoore** [comment]
Fixed in commit 65
